language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
#cache: pip
#install:
#  pip install -r requirements.txt
script:
  python tests.py
  
